[tasks.lint]
description = "Apply lint"
command = "cargo"
args = ["clippy", "--all-features", "--all-targets", "--", "--deny", "warnings"]
dependencies = ["check:fmt", "check:sort"]

[tasks."check:fmt"]
description = "Check format"
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--check"]

[tasks."check:sort"]
description = "Check if Cargo.toml dependencies sorted"
install_crate = { crate_name = "cargo-sort" }
command = "cargo"
args = ["sort", "--workspace", "--check"]
