# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
		ignore:
		# from https://www.youtube.com/watch?v=xUH-4y92jPg
		# patch and minor updates dont' matter for libraries
		# remove this ignore rule if your package has binaries
		- dependency-name: "*"
		  update-types:
		  - "version-update:semver-patch"
		  - "version-update:semver-minor"
