on:
  push:
    tags:
      - 'v*.*.*'

name: cd

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # releaseする際のtagがv0.1.2だとしたら
          # CHANGELOGに[0.1.2]のsectionがないとエラーになる
          changelog: CHANGELOG.md
          title: $tag
          draft: false
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # buildするbinary名
          bin: gh-report-gen
          # linux,macがtarになる
          tar: unix
          zip: windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-cratesio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          # cargo is enough
          profile: minimal
      - name: Setup local credential
        run: cargo login ${CRATES_IO_TOKEN}
        env:
          # 事前にcrates.ioでapi tokenを発行しておく必要がある
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish package
        run: cargo publish
